services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb
    ports:
      - "5432:5432"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
