services:
api:
container_name: token_api
build:
context: .
dockerfile: Dockerfile
ports:
  - "${API_PORT:-3000}:3000"
environment:
  - NODE_ENV=${NODE_ENV:-development}
  - POSTGRES_HOST=db
  - POSTGRES_PORT=5432
  - POSTGRES_USER=${POSTGRES_USER:-postgres}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  - POSTGRES_DATABASE=${POSTGRES_DATABASE:-token-local}
  - SWAGGER_USER=${SWAGGER_USER}
  - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
  - API_PORT=${API_PORT}
depends_on:
db:
condition: service_healthy
networks:
  - token-network
healthcheck:
test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/health" ]
interval: 30s
timeout: 10s
retries: 3
start_period: 40s
restart: unless-stopped
